name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build LibreELEC image
      run: |
        echo "Building LibreELEC image for RPI5..."
        # Add build steps here
        
    - name: Run tests
      run: |
        echo "Running tests..."
        # Add test steps here

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false 